/*
 * generated by Xtext
 */
package io.yaktor.ui.contentassist

import io.yaktor.ui.contentassist.AbstractConversationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ConversationProposalProvider extends AbstractConversationProposalProvider {
}
