/*
 * generated by Xtext
 */
package io.yaktor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;

import io.yaktor.ui.linking.ConversationLinkingDiagnosticMessageProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConversationUiModule extends io.yaktor.ui.AbstractConversationUiModule {
	public ConversationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider() {
		return ConversationLinkingDiagnosticMessageProvider.class;
	}
}
