/*
* generated by Xtext
*/
package io.yaktor.ui.labeling

import com.google.inject.Inject
import io.yaktor.conversation.StateMachine

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
class ConversationLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {

	@Inject
	new(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	def text(StateMachine ele) {
		'FSM'
	}
}
