/*
* generated by Xtext
*/
package io.yaktor;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;
import io.yaktor.conversation.ConversationPackage;
import io.yaktor.domain.DomainPackage;


/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConversationStandaloneSetup extends ConversationStandaloneSetupGenerated{

	public static void doSetup() {
		new ConversationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
    @Override
    public Injector createInjectorAndDoEMFRegistration() {
      EPackage.Registry.INSTANCE.put(ConversationPackage.eINSTANCE.getNsURI(),ConversationPackage.eINSTANCE);
      EPackage.Registry.INSTANCE.put(DomainPackage.eINSTANCE.getNsURI(),DomainPackage.eINSTANCE);
        return super.createInjectorAndDoEMFRegistration();
    }
	
}

