/*
 * generated by Xtext
 */
package io.yaktor;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;

import com.google.inject.Binder;
import com.google.inject.Singleton;
import io.yaktor.converter.ConversationValueConverters;
import io.yaktor.generator.ConversationOutputConfigurationProvider;
import io.yaktor.generator.util.CommentExtractorExtensions;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class ConversationRuntimeModule extends
		io.yaktor.AbstractConversationRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.requestStaticInjection(CommentExtractorExtensions.class);
		binder.bind(IOutputConfigurationProvider.class)
				.to(ConversationOutputConfigurationProvider.class)
				.in(Singleton.class);
	}

	public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
		return ConversationValueConverters.class;
	}
}
