/*
 * generated by Xtext
 */
package io.yaktor.ui.contentassist

import io.yaktor.ui.contentassist.AbstractDomainProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DomainProposalProvider extends AbstractDomainProposalProvider {
}
