/*
 * generated by Xtext
 */
package io.yaktor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DomainUiModule extends io.yaktor.ui.AbstractDomainUiModule {
	public DomainUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
